alerting:
  github:
    repository-url: "https://github.com/Damardwi1/devops-jatim-25"
    token: "<github-token>"  # Ini akan diganti oleh sed command di workflow

endpoints:
  - name: Leantime
    url: "http://lb-807672363.us-east-1.elb.amazonaws.com:80"  # Akan diganti dengan sed command
    interval: 30s
    conditions:
      - "[STATUS] == 200" 
      - "[RESPONSE_TIME] < 300"
    client:
      disable-redirects: true 
    alerts:
      - type: github
        description: "Sensei, Leantime is down! Please check and fix it."

  - name: Gatus
    url: "http://lb-807672363.us-east-1.elb.amazonaws.com:8080"  # Akan diganti dengan sed command
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"
    client:
      disable-redirects: true 
    alerts:
      - type: github
        description: "Sensei, Gatus is down! Please check and fix it."
